import type { M1Output } from "./types";

/**
 * Render a plain-markdown IC memo from an M1Output.
 *
 * Output is hand-tuned for readability in any markdown viewer and for
 * Chrome print-to-PDF. We keep it under ~1,200 words.
 */
export function renderICMemo(output: M1Output, synthesis?: {
  decision: string;
  confidence: number;
  dissents: string[];
  key_drivers: string[];
}): string {
  const { input, scorecards, weightsUsed, topSite, runnerUp, generatedAt } = output;
  const top = scorecards.find((c) => c.site.id === topSite);
  const runner = scorecards.find((c) => c.site.id === runnerUp);

  const lines: string[] = [
    `# Investment Committee Memo — Site Selection`,
    ``,
    `**Prepared by:** DC Control Tower · M1 Site Intelligence`,
    `**Generated:** ${new Date(generatedAt).toUTCString()}`,
    `**Target:** ${input.targetMW} MW · ${input.region} · ${input.workloadProfile}`,
    ``,
    `---`,
    ``,
    `## Recommendation`,
    ``,
    synthesis?.decision ??
      `Primary: **${top?.site.name}** (score ${top?.overallScore.toFixed(1)}/100, 5-yr TCO \$${top?.tco5yrUSDm}M). ` +
      `Secondary: **${runner?.site.name}** (score ${runner?.overallScore.toFixed(1)}/100).`,
    ``,
    synthesis
      ? `**Committee confidence:** ${(synthesis.confidence * 100).toFixed(0)}%`
      : "",
    ``,
    `---`,
    ``,
    `## Ranked candidate sites`,
    ``,
    `| Rank | Site | Country | Overall | TCO (5yr, $M) | Blocking flags |`,
    `|------|------|---------|---------|---------------|----------------|`,
    ...scorecards.map(
      (c) =>
        `| ${c.rank} | ${c.site.name} | ${c.site.country} | ${c.overallScore.toFixed(1)} | ${c.tco5yrUSDm} | ${c.blockingFlags.join(", ") || "—"} |`,
    ),
    ``,
    `## Per-engine breakdown — top site`,
    ``,
    top
      ? [
          `| Engine | Weight | Score | Rationale |`,
          `|--------|--------|-------|-----------|`,
          ...Object.entries(top.engineResults).map(([id, r]) => {
            const w = weightsUsed[id as keyof typeof weightsUsed] ?? 0;
            return `| ${id} | ${(w * 100).toFixed(0)}% | ${r.score} | ${r.rationale.replace(/\|/g, "\\|")} |`;
          }),
        ].join("\n")
      : "(no top site)",
    ``,
    `## Key drivers`,
    ``,
    ...(synthesis?.key_drivers?.length
      ? synthesis.key_drivers.map((d) => `- ${d}`)
      : [
          `- Weighted scoring across 10 dimensions`,
          `- Pre-buildout regulatory screening via shared jurisdictions model`,
          `- 5-yr TCO with country-specific energy escalator`,
        ]),
    ``,
    synthesis?.dissents?.length
      ? [`## Dissenting views`, ``, ...synthesis.dissents.map((d) => `- ${d}`), ``].join("\n")
      : "",
    `---`,
    ``,
    `*This memo is generated by the DC Control Tower. All numeric inputs are sourced from `,
    `public datasets (Ember, IEA, USGS/GEM, Uptime Institute) or industry-standard benchmarks. `,
    `See docs/DATA_SOURCES.md for the full citation ledger.*`,
  ];

  return lines.filter((l) => l !== null && l !== undefined).join("\n");
}
