import type { M2Output } from "./types";

/**
 * Render a customer-ready proposal brief as markdown.
 */
export function renderProposalBrief(output: M2Output, synthesis?: {
  decision: string;
  confidence: number;
  dissents: string[];
  key_drivers: string[];
}): string {
  const { input, fits, costs, sla, comparisons, primaryFacilityId, generatedAt } = output;
  const primary = fits.find((f) => f.facilityId === primaryFacilityId);
  const primaryCost = primary ? costs[primary.facilityId] : null;

  const lines: string[] = [
    `# DAMAC Digital — Capacity Proposal`,
    ``,
    `**Prepared by:** DC Control Tower · M2 Capacity Matcher`,
    `**Generated:** ${new Date(generatedAt).toUTCString()}`,
    `**Workload:** ${input.workload.clusterMW} MW · ${input.workload.gpu} · ${input.workload.shape}`,
    ``,
    `---`,
    ``,
    `## Recommendation`,
    ``,
    synthesis?.decision ??
      (primary
        ? `Primary placement: **${primary.facilityName}** (${primary.country}). ` +
          `Fit score ${primary.fitScore}/100. ${primary.recommendedPhasing}`
        : `No viable primary placement in the current candidate set.`),
    ``,
    `## Ranked facility fit`,
    ``,
    `| Rank | Facility | Country | Fit | Blockers | Phasing |`,
    `|------|----------|---------|-----|----------|---------|`,
    ...fits.map(
      (f, i) =>
        `| ${i + 1} | ${f.facilityName} | ${f.country} | ${f.fitScore.toFixed(1)} | ${f.blockers.join(", ") || "—"} | ${f.recommendedPhasing.replace(/\|/g, "\\|")} |`,
    ),
    ``,
    primaryCost
      ? [
          `## Cost breakdown — primary`,
          ``,
          `- Blended **$${primaryCost.totalUSDPerMWh.toFixed(1)} / MWh** all-in`,
          `- $${(primaryCost.totalUSDPerMonth / 1_000_000).toFixed(2)}M / month`,
          `- 3-yr TCO: **$${primaryCost.threeYearUSDm.toFixed(1)}M**`,
          ``,
          `| Layer | USD / month |`,
          `|-------|-------------|`,
          ...primaryCost.layers.map((l) => `| ${l.layer} | $${l.usdPerMonth.toLocaleString()} |`),
          ``,
        ].join("\n")
      : "",
    `## SLA draft`,
    ``,
    `- **Availability target:** ${sla.availabilityTarget}`,
    `- Power redundancy: ${sla.powerRedundancy}`,
    `- Cooling redundancy: ${sla.coolingRedundancy}`,
    `- Network redundancy: ${sla.networkRedundancy}`,
    `- Incident response: ${sla.incidentResponseMin} min`,
    `- Credits: ${sla.creditsSchedule}`,
    ``,
    `## Competitor benchmarks`,
    ``,
    `| Competitor | Midband $/MWh | DAMAC delta | Note |`,
    `|------------|--------------|-------------|------|`,
    ...comparisons.map(
      (c) =>
        `| ${c.competitorName} | $${((c.pricePerMWhUSDBand[0] + c.pricePerMWhUSDBand[1]) / 2).toFixed(0)} | ${c.priceDeltaPctVsDAMAC >= 0 ? "+" : ""}${c.priceDeltaPctVsDAMAC}% | ${c.notes.replace(/\|/g, "\\|")} |`,
    ),
    ``,
    synthesis?.key_drivers?.length
      ? [`## Key drivers`, ``, ...synthesis.key_drivers.map((d) => `- ${d}`), ``].join("\n")
      : "",
    synthesis?.dissents?.length
      ? [`## Dissents`, ``, ...synthesis.dissents.map((d) => `- ${d}`), ``].join("\n")
      : "",
    `---`,
    ``,
    `*Generated by DC Control Tower. Costs are estimated from public power-price benchmarks; `,
    `final pricing subject to contract. See \`docs/DATA_SOURCES.md\` for citations.*`,
  ];

  return lines.filter((l) => l !== null && l !== undefined).join("\n");
}
