"""
M5 · Build Tower — construction orchestration debate.

Endpoint:
  * /build-orchestrate — 4-agent Sonnet debate + Opus synthesizer (SSE)

Input body is generated by the Next.js M5 deterministic engine and includes:
  - input parameters (MW, complexity, queue months)
  - critical-path milestones with P50/P90 dates
  - risk register with probability / impact / exposure
"""
from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

import yaml
from fastapi import APIRouter, Body
from sse_starlette.sse import EventSourceResponse

import cache as cache_ref
from .runtime import Agent, debate

router = APIRouter()

_ROLES: dict[str, dict[str, Any]] = yaml.safe_load(
    (Path(__file__).parent / "roles" / "m5_build.yaml").read_text()
)


def _agent(key: str, max_tokens: int = 850, temperature: float = 0.35) -> Agent:
    cfg = _ROLES[key]
    return Agent(
        role=key,
        model=cfg["model"],
        system_prompt=cfg["system_prompt"],
        max_tokens=max_tokens,
        temperature=temperature,
    )


def _build_packet(body: dict) -> str:
    build_input = body.get("input", {})
    milestones = body.get("milestones", [])
    risks = body.get("risks", [])

    top_risks = sorted(risks, key=lambda r: r.get("exposureUSDm", 0), reverse=True)[:5]
    critical = [m for m in milestones if m.get("critical")]

    lines = [
        f"Project: {build_input.get('projectName')} ({build_input.get('projectId')})",
        f"Geography: {build_input.get('geography')} · Target MW: {build_input.get('targetMW')}",
        (
            "Scenario controls: "
            f"permitComplexity={build_input.get('permitComplexity')}, "
            f"utilityQueueMonths={build_input.get('utilityQueueMonths')}, "
            f"longLeadTightness={build_input.get('longLeadTightness')}, "
            f"epcReadiness={build_input.get('epcReadiness')}, "
            f"contingencyPct={build_input.get('contingencyPct')}"
        ),
        "",
        "Critical milestones (P50/P90):",
    ]

    for m in critical:
        lines.append(
            (
                f"- {m.get('name')}: duration={m.get('durationDays')}d, "
                f"slip={m.get('slipProbabilityPct')}%, "
                f"P50={m.get('p50Finish')}, P90={m.get('p90Finish')}"
            )
        )

    lines.append("")
    lines.append("Top risk exposures:")
    for r in top_risks:
        lines.append(
            (
                f"- {r.get('title')}: prob={r.get('probabilityPct')}%, "
                f"impact={r.get('impactDays')}d, impactUSDm={r.get('impactUSDm')}, "
                f"exposureUSDm={r.get('exposureUSDm')}"
            )
        )

    lines.append("")
    lines.append(
        "Decision requested: what is most likely to delay energization, what interventions "
        "should be executed this week, and which owner should be accountable for each action?"
    )
    return "\n".join(lines)


@router.post("/build-orchestrate")
async def build_orchestrate(body: dict = Body(...)) -> EventSourceResponse:
    preset_id = body.get("preset_id")
    cached = cache_ref.read(preset_id, body) if preset_id else None
    if cached is not None:
        async def replay():
            for frame in cached.get("frames", []):
                yield {"event": frame.get("event", "message"), "data": json.dumps(frame["data"])}
                await asyncio.sleep(0.01)
        return EventSourceResponse(replay())

    analysts = [
        _agent("procurement_analyst"),
        _agent("permit_analyst"),
        _agent("utility_analyst"),
        _agent("epc_risk_analyst"),
    ]
    synthesizer = _agent("build_synthesizer", max_tokens=1200, temperature=0.3)
    question = _build_packet(body)

    async def event_gen():
        collected: list[dict] = []
        async for evt in debate(agents=analysts, question=question, synthesizer=synthesizer, rounds=1):
            t = evt.get("type")
            if t == "phase":
                data = {"phase": evt.get("phase"), "agent": evt.get("agent")}
                collected.append({"event": "phase", "data": data})
                yield {"event": "phase", "data": json.dumps(data)}
            elif t == "token":
                data = {"agent": evt["agent"], "delta": evt["delta"]}
                collected.append({"event": "token", "data": data})
                yield {"event": "token", "data": json.dumps(data)}
            elif t == "done":
                data = evt.get("result") or evt
                collected.append({"event": "done", "data": data})
                yield {"event": "done", "data": json.dumps(data)}
            elif t == "error":
                yield {"event": "error", "data": json.dumps({"message": evt.get("message", "unknown")})}

        if preset_id and collected:
            cache_ref.write(preset_id, body, {"frames": collected})

    return EventSourceResponse(event_gen())
